- category: potential
  customVariables: []
  description: Explicit Config Server connection info found in configuration file
  effort: 0
  labels:
  - konveyor.io/source=springboot
  - konveyor.io/target=azure-spring-apps
  - konveyor.io/target=azure-appservice
  - konveyor.io/target=azure-aks
  - konveyor.io/target=azure-container-apps
  - Spring Cloud Config
  links:
  - title: Remove restricted configurations
    url: https://learn.microsoft.com/azure/developer/java/migration/migrate-spring-cloud-to-azure-spring-apps?pivots=sc-standard-tier#remove-restricted-configurations
  - title: Prepare the Spring Cloud Config server
    url: https://learn.microsoft.com/azure/developer/java/migration/migrate-spring-cloud-to-azure-spring-apps?pivots=sc-standard-tier#prepare-the-spring-cloud-config-server
  message: |-
    The application uses a Spring Cloud Config Server connection string.

     If you are migrating to Azure Spring Apps, the connection info of Config Server will be injected automatically upon app start.
     Find any explicit configurations of config server connection info:

     If configured in **configuration files**: they will be ignored and overrided by Azure Spring Apps.

     If configured in **command line parameters**, **Java system attribute**, **environment variable**: they need to be removed or you might experience conflicts and unexpected behavior.

     Configure the config server after creating an Azure Spring Apps instance.
  ruleID: spring-boot-to-azure-config-server-01000
  tag:
  - Spring Cloud Config
  when:
    builtin.filecontent:
      filePattern: .*\.(properties|yaml|yml)
      pattern: spring\.config\.import|spring\.cloud\.config\.uri
- category: potential
  customVariables: []
  description: Spring Cloud Config Server found
  effort: 0
  labels:
  - konveyor.io/source=springboot
  - konveyor.io/target=azure-spring-apps
  - konveyor.io/target=azure-appservice
  - konveyor.io/target=azure-aks
  - konveyor.io/target=azure-container-apps
  - Spring Cloud Config
  links:
  - title: Prepare the Spring Cloud Config server
    url: https://learn.microsoft.com/azure/developer/java/migration/migrate-spring-cloud-to-azure-spring-apps?pivots=sc-standard-tier#prepare-the-spring-cloud-config-server
  message: |-
    The application uses Spring Cloud Config Server.

     If you are migrating to Azure Spring Apps, Config Server (Standard Tier) or Application Configuration Service (Enterprise Tier) will be hosted for you.
     You can just configure the config server after creating an Azure Spring Apps instance
  ruleID: spring-boot-to-azure-config-server-02000
  tag:
  - Spring Cloud Config
  when:
    or:
    - java.dependency:
        lowerbound: 0.0.0
        name: org.springframework.cloud.spring-cloud-config-server
    - java.referenced:
        location: IMPORT
        pattern: org.springframework.cloud.config.server.EnableConfigServer.EnableConfigServer
